/*
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def static allowedControllers = ['home', 'help', 'feed', 'news','meditation','community','wellbeing','buddhism','aboutUs','commentable']
    def static allowedActions = ['home','frob','slideshow','view', 'index', 'src', 'thumbnail', 'welcome', 'requestPermission', 'requestRoles', 'error', 'info','list','all','query','send','calendar','subscribe','events','event','current','future','regular','displayAll','display']

    def filters = {
        loginCheck(controller:'*', action:'*') {
            before = {
                log.debug "Checking if authentication is required..."
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) {
                    return true
                } else if (!actionName) {
                    return true
                } else if (allowedControllers.contains(controllerName) || allowedActions.contains(actionName)){
                    return true
                }
                
                log.debug "Authentication required calling accessControl()"
                // Access control by convention.
                accessControl(auth:true)
            }
        }
    }
}
