/*
 * Copyright © 2010 Leanne Northrop
 *
 * This file is part of Samye Content Management System.
 *
 * Samye Content Management System is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Samye Content Management System is distributed in the hope that it will be
 * useful,but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Samye Content Management System.
 * If not, see <http://www.gnu.org/licenses/>.
 *
 * BT plc, hereby disclaims all copyright interest in the program
 * “Samye Content Management System” written by Leanne Northrop.
 */

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def static allowedControllers = ['home', 'help', 'feed', 'news','meditation','community','wellbeing','buddhism','aboutUs','commentable','greenmail']
    def static allowedActions = ['home','frob','slideshow','view', 'index', 'src', 'thumbnail', 'welcome', 'requestPermission', 'requestRoles', 'error', 'info','list','all','query','send','calendar','subscribe','events','event','current','future','regular','displayAll','display']

    def filters = {
        loginCheck(controller:'*', action:'*') {
            before = {
                log.debug "Checking if authentication is required..."

                // Ignore direct views (i.e. the default main index page).
                if (!controllerName) {
                    return true
                } else if (!actionName) {
                    return true
                } else if (allowedControllers.contains(controllerName) || allowedActions.contains(actionName)){
                    return true
                }
                
                log.debug "Authentication required calling accessControl()"
                // Access control by convention.
                accessControl(auth:true)
            }
        }
    }
}
